#ifndef LIBCONNMAN_QT_H
#define LIBCONNMAN_QT_H

#ifdef LIBCONNMAN_QT_LIBRARY_BUILD
  #define LIBCONNMAN_QT_EXPORT Q_DECL_EXPORT
#else
  #define LIBCONNMAN_QT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBCONNMAN_QT_H
